### ISSUE TITLE
Wrong port PX4 SITL - QGC

### ISSUE THREAD

**Issue by boris-gu** [PX4/PX4-user_guide#1000]
The documentation says that for SITL it is port 14570, although in fact it is port 18570.
https://docs.px4.io/master/en/test_and_ci/docker.html#qgroundcontrol
The same error is present in the image here:
https://docs.px4.io/master/en/simulation/ros_interface.html#ros-with-gazebo-simulation

![image](https://user-images.githubusercontent.com/44787162/104995847-f2e92980-5a37-11eb-8cae-4d6ca589b78d.png)

**Comment by boris-gu** [comment]
As a result, I managed to connect QGC to the simulation in the docker container by writing these values:
![image](https://user-images.githubusercontent.com/44787162/104996007-35ab0180-5a38-11eb-9e7e-66749efb9497.png)

**Comment by hamishwillee** [comment]
The SITL ports are [documented here](https://docs.px4.io/master/en/simulation/#sitl-simulation-environment) - as these indicate QGC normally connects on 14550

Can you please try that? Either way the 14570 is probably wrong.

**Comment by boris-gu** [comment]
@hamishwillee Forgive me, I do not quite understand this phrase: "18570 is supposed to be for sending to rather than listening for connections". English is not my native language.
If I understand correctly, it works like this - QGC listens on port 14550, on which it receives messages from the PX4 autopilot. In turn, the PX4 autopilot listens on port 18570 to receive information from the QGC.

**Comment by hamishwillee** [comment]
@boris-gu My understanding is that what normally happens is that QGC "listens" to port 14550 on the computer running PX4 - ie it waits for mavlink traffic before it starts broadcasting its heartbeat. The address it sends the UDP traffic back to is in the packet it gets which I presume is 18570. 

I could be wrong on this, but I do know that 14550 works in almost every scenario. So I am hoping you can try that out and confirm.

 I have also asked for clarification in the [#simulation slack channel](https://px4.slack.com/archives/CL3LV4FUH/p1611108528005100))

**Comment by hamishwillee** [comment]
@bkueng can you advise on this one? 

CI/Docker docs suggest connecting to PX4 hosted on docker using 14570. The Simulation docs suggest 14550. This issue suggests 18570, and the CI docs do mention configuration file in which this port does appear.

**Comment by hamishwillee** [comment]
@julianoes Can you comment on this. Getting a similar comment in #1000
