### ISSUE TITLE
Inconsistency in IDE recommendations

### ISSUE THREAD

**Issue by max11gen** [PX4/PX4-user_guide#1022]
The IDEs that are recommended in the user guide are inconsistent. If you go to [Development-->Toolchain Installation](https://docs.px4.io/master/en/dev_setup/dev_env.html) there is a whole section about [VSCode](https://docs.px4.io/master/en/dev_setup/vscode.html). [Building the Code](https://docs.px4.io/master/en/dev_setup/building_px4.html) on the other hand clearly states that

> The PX4 system supports Qt Creator, Eclipse and Sublime Text. Qt Creator is the most user-friendly variant and hence the only officially supported IDE. 

I assume that the information given in the Building the Code section is outdated. However, I'm not really sure about this. A clarification and a fix to the docs would be nice.

**Comment by hamishwillee** [comment]
Thanks. You're correct. I will tidy this Monday/Tuesday. Vscode is now recommended.
