### ISSUE TITLE
Typo in markdown format in Chinese translation

### ISSUE THREAD

**Issue by InTereSTingHE** [PX4/PX4-user_guide#1143]
In /flight_modes/offboard.md, about the SET_POSITION_TARGET_GLOBAL_INT. It should be like this:

![2021-03-25 11-14-21 的屏幕截图](https://user-images.githubusercontent.com/32561116/112413496-455a0580-8d5b-11eb-9cf8-caaa132e25c4.png)
    But for some reason it's like this in Chinese translation:

![2021-03-25 11-15-21 的屏幕截图](https://user-images.githubusercontent.com/32561116/112413580-6884b500-8d5b-11eb-8f9b-9f5dee5d28fa.png)

I go to the source code and find out that here miss some space:

![2021-03-25 11-16-39 的屏幕截图](https://user-images.githubusercontent.com/32561116/112413695-9833bd00-8d5b-11eb-8cee-c093d5c34665.png)

In English version it's like this:

![2021-03-25 11-17-38 的屏幕截图](https://user-images.githubusercontent.com/32561116/112413768-ba2d3f80-8d5b-11eb-8159-4a5438b89022.png)

Hope you can fix it. Thanks

**Comment by hamishwillee** [comment]
Thanks for letting me know. Some of this is auto generated by crowdin translation tool. I have tried to fix it, but may not work. I won't find out until it syncs.  I will leave this open though.
