### ISSUE TITLE
Need a page that explains how to find a parameter

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-user_guide#122]
@hamishwillee Here is the image for it. Just need a central page for this and general settings. Then we can reference statements like "set parameter ABC to 1.0" to that page.

<img width="1120" alt="find_param" src="https://user-images.githubusercontent.com/1208119/34456315-af31bafe-ed93-11e7-8e6a-02f369be5601.png">

**Comment by hamishwillee** [comment]
The [parameters doc](https://docs.qgroundcontrol.com/en/SetupView/Parameters.html) in QGC should be usable for this purpose but is a bit out of date. I've updated it (https://github.com/mavlink/qgc-user-guide/pull/125) and I'll cross post with minor modification into the user guide.

**Comment by hamishwillee** [comment]
Addressed by #126
