### ISSUE TITLE
Parameter C++ API documentation

### ISSUE THREAD

**Issue by pjdewitte** [PX4/PX4-user_guide#1256]
The documentation at https://docs.px4.io/master/en/advanced/parameters_and_configurations.html#c-api seems outdated. It doesn't match with the module template in the PX4 codebase.

Issues I can see:

- (minor) Is this really needed in the *cpp* file? It seems to be omitted in many modules.

        #include <uORB/topics/parameter_update.h>

- `(...) : ModuleParams(nullptr)` and why you should provide nullptr or something else is missing in the documentation.

- The following code snippet is hardly used in the PX4 codebase and seems no longer needed:

        int parameter_update_sub = orb_subscribe(ORB_ID(parameter_update));

- The code snippet for `Module::parameters_update` is different from `TemplateModule::parameters_update`, which is confusing.

- API docs (nor example code) shows how to use the parameter and how the system reacts (e.g. `.get()`, `.commit()`, ... methods)

- There are no docs on how to add your own parameters

I propose someone who understands the parameter system in and out updates the documentation. I'd be happy to review from my perspective.

**Comment by bkueng** [comment]
Yes a couple of things need to be updated.

>  (minor) Is this really needed in the cpp file?

No, just in the header

> (...) : ModuleParams(nullptr) and why you should provide nullptr or something else is missing in the documentation.

It's the parent (for the parameter updates), so for the main module, it's null.

> The following code snippet is hardly used in the PX4 codebase and seems no longer needed:

Correct, should be changed to the C++ Subscription class.

> API docs (nor example code) shows how to use the parameter and how the system reacts (e.g. .get(), .commit(), ... methods)

Best to look at the code: https://github.com/PX4/PX4-Autopilot/blob/master/platforms/common/include/px4_platform_common/param.h#L129

> There are no docs on how to add your own parameters

Could maybe be more explicit, but it's here: https://docs.px4.io/master/en/advanced/parameters_and_configurations.html#parameter-metadata
