### ISSUE TITLE
中文翻译和英文版图片不对应

### ISSUE THREAD

**Issue by Flordsky** [PX4/PX4-user_guide#1320]
![image](https://user-images.githubusercontent.com/42493042/120923406-f3d9d980-c700-11eb-9af5-9c234701db87.png)
![image](https://user-images.githubusercontent.com/42493042/120923414-005e3200-c701-11eb-91b3-f76c3e71d226.png)

**Comment by hamishwillee** [comment]
Can you post the question in English?

**Comment by Ionstream** [comment]
He's trying to say that the code snippet on the mandarin and english docs do not match up.

**Comment by hamishwillee** [comment]
Ah, thank you. We use crowdin to translate : http://docs.px4.io/master/zh/contribute/translation.html

Would be very pleased to accept @Flordsky into the crowdin translator group to fix it

**Comment by mrpollo** [comment]
Can someone please translate the erroneous section and help us fix it? @bys1123

**Comment by Flordsky** [comment]
> Ah, thank you. We use crowdin to translate : http://docs.px4.io/master/zh/contribute/translation.html
> 
> Would be very pleased to accept @Flordsky into the crowdin translator group to fix it

I had joined the group, and I will try to fix it when I was free.

**Comment by Flordsky** [comment]
> Ah, thank you. We use crowdin to translate : http://docs.px4.io/master/zh/contribute/translation.html
> 
> Would be very pleased to accept @Flordsky into the crowdin translator group to fix it

I had joined the group, and I would try to fix it when I was free.

**Comment by hamishwillee** [comment]
@Flordsky - when you have time is excellent. Thank you.

**Comment by hamishwillee** [comment]
FYI @bys1123  Closing as this is something to deal with in Crowdin.
