### ISSUE TITLE
Update UAVCAN Firmware Update Instructions

### ISSUE THREAD

**Issue by AlexKlimaj** [PX4/PX4-user_guide#1424]
The UAVCAN firmware update instructions are out of date and don't reflect the new system that only requires the binary to be placed on the root of the sd card.

https://docs.px4.io/master/en/uavcan/node_firmware.html

**Comment by hamishwillee** [comment]
@AlexKlimaj Can you create a PR please?

**Comment by AlexKlimaj** [comment]
@pavel-kirienko Are the instructions still correct for the Zubax products?

**Comment by pavel-kirienko** [comment]
@AlexKlimaj Zubax products (or any other UAVCAN devices) are invariant to the internals of the bootloader server. Instructions specific to Sapog are already available at https://github.com/PX4/sapog/ (and they are more up-to-date), I don't think it makes sense to keep them in the PX4 Guide. Maybe the same is true for the Thiemar ESC (does anybody use them?)

**Comment by samchamberlin** [comment]
@pavel-kirienko is there a link to any documentation that Zubax would want to keep on this page?

**Comment by pavel-kirienko** [comment]
There is no such documentation at the moment.

**Comment by hamishwillee** [comment]
So the fix would be to  (?)
- note that firmware build process is firmware dependent, and point to each firmware instructions - e.g. Sapog: https://github.com/PX4/sapog/#firmware
- Explain where to put the files and how to start the firmware process
- Delete the rest

Correct?

**Comment by hamishwillee** [comment]
@AlexKlimaj ^^^ Is this enough to information for us to move forward on this?

**Comment by AlexKlimaj** [comment]
> 
> 
> @AlexKlimaj ^^^ Is this enough to information for us to move forward on this?

Yep, that should be good!

**Comment by hamishwillee** [comment]
Great.  I'll leave it with you guys then.

**Comment by hamishwillee** [comment]
All fixed thanks to @samchamberlin ! Thanks for keeping on top of this .
