### ISSUE TITLE
MPC_LAND_ALT1 has different default values on different pages

### ISSUE THREAD

**Issue by rzzuozuo** [PX4/PX4-user_guide#1489]
https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_VEL_MANUAL
![image](https://user-images.githubusercontent.com/26183186/129871489-63f320b3-0e11-4eb8-9c5a-797e68ba64ae.png)

https://docs.px4.io/master/en/flight_modes/position_mc.html
![image](https://user-images.githubusercontent.com/26183186/129871615-1917784f-3d2e-46df-912f-e869dc3587f7.png)

**Comment by hamishwillee** [comment]
Thank you. Fixed in #1492
