### ISSUE TITLE
A wrong mode name in Altitude Mode(mc) -technical summary

### ISSUE THREAD

**Issue by rzzuozuo** [PX4/PX4-user_guide#1490]
A wrong mode name in Altitude Mode(mc) -technical summary

https://docs.px4.io/master/en/flight_modes/altitude_mc.html
![image](https://user-images.githubusercontent.com/26183186/129993950-d24a23d3-ced6-4f9f-ac06-4e6243d30f4a.png)
There should be RC/Altitude mode or RC mode.

Similar issues in fw.

**Comment by hamishwillee** [comment]
No, this is fine. It reads as "RC or manual mode like".

**Comment by rzzuozuo** [comment]
I see, thank you.
