### ISSUE TITLE
A wrong make parameter for Pixhark 4

### ISSUE THREAD

**Issue by rzzuozuo** [PX4/PX4-user_guide#1500]
https://docs.px4.io/master/en/dev_setup/building_px4.html
There should be v5 for Pixhark 4.
![image](https://user-images.githubusercontent.com/26183186/130427377-aaebdf8d-d19b-478d-9ac2-a8e7b1770135.png)

**Comment by hamishwillee** [comment]
Thanks very much. Fixed in https://github.com/PX4/PX4-user_guide/commit/2baa7b04736c5b36aaef26a2c31d290ba63d2d48
