### ISSUE TITLE
How to translate the left side

### ISSUE THREAD

**Issue by rzzuozuo** [PX4/PX4-user_guide#1501]
![1629712877(1)](https://user-images.githubusercontent.com/26183186/130428979-9aa1d4ad-6beb-4eea-a35e-faf676ae169c.png)

SUMMARY.md has been translated.
https://github.com/PX4/PX4-user_guide/blob/master/zh/SUMMARY.md
![1629712994(1)](https://user-images.githubusercontent.com/26183186/130429423-76174d99-4b0a-4c49-bed4-e950c22c1a5a.png)

**Comment by hamishwillee** [comment]
Same way as everything else - in crowdin. So if you are logged in to Crowdin the file you would translate is this one: https://crowdin.com/translate/px4-user-guide/4/en-zhcn?filter=basic&value=0

Yes, as you note, that is SUMMARY.md.
