### ISSUE TITLE
In 'GPS & Compass' page, Here3 information is not correct

### ISSUE THREAD

**Issue by bigbellmercy** [PX4/PX4-user_guide#1600]
In the first table on ['GPS & Compass'](https://github.com/PX4/PX4-user_guide/tree/master/en/gps_compass) page,
the following information for Here3 GNSS module should be changed according to [the vendor's manual](https://docs.cubepilot.org/user-guides/here-3/here-3-manual):

1. CubePilot Here3 CAN GNSS GPS (M8N) --> CubePilot Here3 CAN GNSS GPS (**M8P**)
2. In GPS column, M8N --> **M8P**
3. In RTK column, it should be marked as check sign.

**Comment by hamishwillee** [comment]
Thanks very much. I'm actually not certain PX4 supports RTK over UAVCAN. Am checking on Slack general channel.
