### ISSUE TITLE
Doc Bug: Flight Modes · PX4 User Guide

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-user_guide#181]
[Flight Mode Overview > Manual/Stabilized mode](https://docs.px4.io/en/getting_started/flight_modes.html#manualstabilized-mode) - @tubeme the image isn't quite right.

1. On right, text "Level Flight / Stabilized" - "Stabilized" is miss-spelled in image.
2. The left stick is labeled rate controlled. But actually only the yaw input is rate controlled, not the throttle. 

IMO for this case having the text label "Angle" and "Rate controlled" isn't useful because it won't mean anything to most users. You and I know that angle implies that the vehicle will move left/right or forward/back at a constant speed for the current throttle, but not a new user.

**Comment by tubeme** [comment]
I agree for the Angle and rate control... Could not find a better words to describe it...

Here are the corrected images.
![manual stabilized fw](https://user-images.githubusercontent.com/12617619/37894844-3f0fd8c6-30e8-11e8-856b-3e3e65d75fb4.png)
![manual stabilized mc](https://user-images.githubusercontent.com/12617619/37894846-3f364812-30e8-11e8-8445-75634578a033.png)

**Comment by hamishwillee** [comment]
Thanks @tubeme . For the "FW" image, could you please also change the spelling "Glyde" to "Glide"?

**Comment by hamishwillee** [comment]
> I agree for the Angle and rate control... Could not find a better words to describe it...

Angle and angle rate control are fine. The problem is that the Up/Down stick is not rate controlled - only the spin (yaw) is. That said, I don't see any easy way to correct it - this looks unbalanced:
![image](https://user-images.githubusercontent.com/5368500/37943762-a5b52e82-31c4-11e8-8f0d-83c7ed6e0346.png)
