### ISSUE TITLE
Error in tailsitter motor numbering

### ISSUE THREAD

**Issue by zlite** [PX4/PX4-user_guide#1849]
On [this page](https://docs.px4.io/v1.12/en/airframes/airframe_reference.html), the VTOL Quad Tailsitter motor numbering is wrong (and doesn't agree with the picture). Should be as shown here

![tailsitter](https://user-images.githubusercontent.com/18071/164373266-71ea91e4-d288-4cfd-9ee1-fd670b212e5f.png)

**Comment by hamishwillee** [comment]
Thanks very much - that's been wrong for a very long time. I have put in a fix here: https://github.com/PX4/PX4-Autopilot/pull/19518

**Comment by hamishwillee** [comment]
@zlite I completely agree. When I recently updated these docs http://docs.px4.io/master/en/frames_vtol/tailsitter.html#tailsitter-airframes I originally intended to use the diagrams from airframe reference but they were too confusing.

However I don't have the SVG skills to do this (I tried, but I don't). So I won't be touching it.

**Comment by zlite** [comment]
Even something as simple as extending the arm lines for the upper motors, as shown here, would give a clue. (assuming that I have indeed intuited the right orientation)
![Screenshot 2022-04-23 180048](https://user-images.githubusercontent.com/18071/164954131-db4f2f57-ae7b-4549-b09b-6d57e879e9a2.png)

**Comment by zlite** [comment]
I confirmed with Roman Bapst, the maintainer, that the above redrawing is correct

**Comment by hamishwillee** [comment]
Well, I'm still not good at SVG, but why not https://github.com/PX4/PX4-user_guide/pull/1864
