### ISSUE TITLE
External Sensors in HITL

### ISSUE THREAD

**Issue by daylanc** [PX4/PX4-user_guide#1895]
Hello,
Question about using external sensors in HITL. I want to test an autonomous landing sensor in HITL before testing in the field. Is this possible in HITL? In other words, our sensor will command the quadcopter to fly a certain direction given its position in relation to the landing pad. Can this behavior be simulated in HITL?

**Comment by hamishwillee** [comment]
Best place to ask this question is in PX4 slack or the discussion boards.
