### ISSUE TITLE
E: Unable to locate package ros-galactic-rmw-fastrtps

### ISSUE THREAD

**Issue by sumedhreddy90** [PX4/PX4-user_guide#1960]
From the docs, I did try to follow below installation process to install fastrtps with galactic. But the package was not being fond. Let me know if I am missing something.
 
"For ROS2 Galactic and above, one has to install the rmw implementation through apt using apt install ros-galactic-rmw-fastrtps, since the default middleware for Galactic and above is CycloneDDS and the FastDDS middleware doesn't come installed by default."

```
sumedh@starfleeet:~/px4_workspace$ rosversion -d
galactic
```

To reproduce the Issue:
```
sumedh@starfleeet:~/px4_workspace$ sudo apt install ros-galactic-rmw-fastrtps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-galactic-rmw-fastrtps
```

**Comment by hamishwillee** [comment]
Closing. Old, and no response.
