### ISSUE TITLE
uorb_graph: subscriber link hide publisher link if both are present

### ISSUE THREAD

**Issue by beniaminopozzan** [PX4/PX4-user_guide#2010]
When a module both subscribes and publishes to a uorb topic then in the uorb graph two links are drawn. However the link of the publisher, which is drawn in dashed line, is hided by the solid line of the subscriber link.

This can be seen in the _vehicle_control_mode_ topic, which is both published and subscribed by the _commander_ module.

What about adding a third line style for links that must represent both subscription and publication?

**Comment by hamishwillee** [comment]
@bkueng A question for you!

**Comment by bkueng** [comment]
Sure, no objections.
I'm about to remove this particular case in commander though.

**Comment by hamishwillee** [comment]
My assumption is that you will close this when any required work is done @bkueng . Cheers.

**Comment by bkueng** [comment]
@beniaminopozzan any chance you can create a PR?

**Comment by beniaminopozzan** [comment]
@bkueng sorry for the wait
