### ISSUE TITLE
Error in PX4-user_guide/en/ros/mavros_custom_messages.md

### ISSUE THREAD

**Issue by Edekheh** [PX4/PX4-user_guide#2116]
Hi, I've been trying to compile it but there is an error in file : /PX4-Autopilot/src/modules/key_receiver/key_receiver.cpp

For compile correctly you must change lines : 
21         { .fd = keyboard_sub_fd,   .events = POLLIN },
to : 
             { .fd = key_sub_fd,   .events = POLLIN },
Then add logger library for PX4_ERR messages : 
#include <px4_platform_common/log.h>

Hope You can modify instructions or correct me if I am wrong :)

**Comment by hamishwillee** [comment]
@Edekheh Thanks. what versions did you test this against? As per the document, it was tried with:

- Ubuntu: 20.04
- ROS: Noetic
- PX4 Firmware: v1.12.3

Do you think you could create a PR for the required changes? That would remove any possibility of me making a copy/paste error.

**Comment by Edekheh** [comment]
@hamishwillee Sorry for late reply, i could try to create PR if You could link me to any guide/docs about how to do it properly.
And i tested in on latest 1.13 version of PX4, ROS:Noetic, Ubuntu 20.04. I think on 1.12.3 these changes are necessary too .

**Comment by steamfoundry** [comment]
If your looking for some simple instructions on how to contribute, I liked the Adafruit walkthrough here. 
<https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control>
