### ISSUE TITLE
autotune fixed wing QGCS tab missing

### ISSUE THREAD

**Issue by x-sven** [PX4/PX4-user_guide#2149]
Hi, i would like to use autotuning for a generic fixed wing. However, using latests QGCS and PX4 firmware stack, the tab for PID tuning is missing for fixed wing configurations (VTOL or quad seems working). Documentation does not match, see: https://docs.px4.io/main/en/config/autotune.html

Vehicle setup > PID Tuning does not show up, Autotune may be enabled by flight mode selector, but unsure if that works or is desired. 
Are there any recommendations? THX Sven

**Comment by Jaeyoung-Lim** [comment]
@x-sven This has been fixed in https://github.com/mavlink/qgroundcontrol/pull/10384

**Comment by x-sven** [comment]
Ok, thanks for the quick reply. Can you tell me which stable QGCS version will be released with this fix?
