### ISSUE TITLE
Multicopter PID Tuning Guide update and generic racer setup page

### ISSUE THREAD

**Issue by hamishwillee** [PX4/PX4-user_guide#244]
[Multicopter PID Tuning Guide · PX4 User Guide](https://docs.px4.io/en/advanced_config/pid_tuning_guide_multicopter.html) needs a major overhaul
- Vehicles not actually tuned in this way. 
- MC_YAW_FF is likely to be removed soon 

Also have generic racer setup page. 

Draft to be done by @bkueng with help from @MaEtUgR and @RomanBapst 

This originates from discussion here: https://github.com/PX4/px4_user_guide/pull/242#issuecomment-391965843

**Comment by MaEtUgR** [comment]
@hamishwillee Good idea. You could assign me as well.

**Comment by bkueng** [comment]
FYI I started working on a racer page already. I'll probably do the tuning page as well.

**Comment by MaEtUgR** [comment]
@bkueng That's perfect, I planned to postpone this if I had to write up myself. Let me know if I can help and/or review anything.
