### ISSUE TITLE
Axis colors for flight controller / sensor orientation docs

### ISSUE THREAD

**Issue by mortenfyhn** [PX4/PX4-user_guide#2454]
Hi!

Regarding this page: https://docs.px4.io/main/en/config/flight_controller_orientation.html

and specifically these drawings:

![image](https://user-images.githubusercontent.com/6639836/231745961-fa6b9a04-6299-4125-87f6-bc0a7641c6a5.png)

Is there a reason why the coordinate frame axis arrows x-y-z are colored red-blue-green, respectively, instead of red-green-blue? In my experience, red-green-blue is the usual convention, possibly because it matches the common "RGB" color ordering.

**Comment by hamishwillee** [comment]
No reason. I don't see it as a bug, but if someone wants to provide a version that matches then fine. However we don't have the source files, so it would be annoying pixel updates.

**Comment by mortenfyhn** [comment]
I understand, thank you for the swift feedback! I might take the time to do this some day, but for now I'll close this.

**Comment by hamishwillee** [comment]
Makes sense!
