### ISSUE TITLE
Omnibus F4 SD hex file link in v1.11 docs broken

### ISSUE THREAD

**Issue by junwoo091400** [PX4/PX4-user_guide#2492]
## About
In the v1.11 documentation: https://docs.px4.io/v1.11/en/flight_controller/omnibus_f4_sd.html#bootloader

The file linked as https://github.com/PX4/px4_user_guide/raw/master/assets/flight_controller/omnibus_f4_sd/omnibusf4sd_bl_d52b70cb39.hex is an invalid link, because the branch name should be `main`, not `master`

## Solution
We need to change the link of the v1.11 docs. @hamishwillee How can we change the 1.11 documentation files?

**Comment by hamishwillee** [comment]
The short answer is that we don't maintain the old versions - we don't have time or resource. I would however check the main is correct. (please do).
I hope to drop v1.11 after v1.14 comes out to encourage people to move up.

For this case, I have fixed it.

If you want to spend your time on this sort of thing, then the source code for different versions are in branches - i.e. here https://github.com/PX4/PX4-user_guide/blob/v1.11/en/flight_controller/omnibus_f4_sd.md 

If you modify the file it should automatically rebuild in CI. Takes a while though.
