### ISSUE TITLE
Running Offboard Sensor Combined Example in Build Terminal Not Recommended

### ISSUE THREAD

**Issue by secondsensei** [PX4/PX4-user_guide#2557]
ROS2 User Guide > Build ROS 2 Workspace > Running the Example says to source the `local_setup.bash` in the same terminal where `px4_msgs` and `px4_ros_com` was just built. ROS2 recommends not to source an overlay in the same terminal where it was built. ROS2 Humble documentation says it may lead to [complex issues](https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.html#source-the-overlay).

**Comment by Jaeyoung-Lim** [comment]
@secondsensei Please consider improving the instructions by making a Pull request on the documentation

**Comment by Jaeyoung-Lim** [comment]
@secondsensei Please consider improving the instructions by making a Pull request on the documentation

**Comment by hamishwillee** [comment]
Thanks. Creating a PR is great, particularly for small changes, as you're the person who knows most about the problem. As there was no response and this seems important I have added one in https://github.com/PX4/PX4-user_guide/pull/2562
