### ISSUE TITLE
kakute h7 mini v1.2(maybe) can't save params

### ISSUE THREAD

**Issue by kokoory** [PX4/PX4-user_guide#2595]
I build the main repo and upload the firmware. but I can't save the params. So,I check the previous code. It is well coded. I read relating post but I cannot find the solution.

Thanks,

**Comment by hamishwillee** [comment]
There is not enough information for me to evaluate this or help.
In any case, the right thing to do is to repost this query on https://discuss.px4.io/ with the following information:

1. What version of PX4 are you trying? 
2. How you built it
3. How are you trying to save params? Via QGC, using some command? 
4. What errors are you seeing?
