### ISSUE TITLE
doc: How to add a new board in building a system

### ISSUE THREAD

**Issue by xianglunkai** [PX4/PX4-user_guide#2607]
Hello! I want to imitate the Blue Board and add a new control board, which is based on Linux. Currently, I haven't seen any relevant guidelines in the doc.

Thank you!

**Comment by hamishwillee** [comment]
Hi @xianglunkai 

If you can't find anything in this section http://docs.px4.io/main/en/hardware/board_support_guide.html then probably there isn't anything. You'd have to copy the existing setup and ask questions on the discussion forums.

At the end of the process you could help create new docs for this use case.
