### ISSUE TITLE
Could not flash firmware on Kakute H7V2

### ISSUE THREAD

**Issue by chen716** [PX4/PX4-user_guide#2614]
Hi, I'm trying to flash bootloader to a new purchased Kakute H7v2 following this guide: https://docs.px4.io/main/en/flight_controller/kakuteh7v2.html

I have downloaded betaflight configurator and downloaded kakute h7v2 bootloader from here (https://github.com/PX4/PX4-user_guide/tree/main/assets/flight_controller/kakuteh7v2, I've also tried the one from the guide's link as well). 
![Capture](https://github.com/PX4/PX4-user_guide/assets/21245905/220d8dd2-b466-49d6-bd11-86d67304702b)
When I put the fcu into DFU mode and start to flash, it shows "Firmware image Contains addresses not found on target devices", how could I resolve this? 
P.S. The configurator did work on flashing ardupilot on, but after flashing windows(10) shows  hardware malfunctioned, and only option is to flash betaflight back on... 

Thanks

**Comment by hamishwillee** [comment]
Did you see this? https://docs.px4.io/main/en/advanced_config/bootloader_update_from_betaflight.html#dfu-util
