### ISSUE TITLE
Add mode to connect multicopter PWM straight to AUX and document it

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/PX4-user_guide#271]
@bkueng @MaEtUgR We should document for racing setups how to essentially flip FMU and IO outputs.

**Comment by bkueng** [comment]
Yep, already done here: https://docs.px4.io/en/advanced_config/racer_setup.html#control_latency via SYS_USE_IO param.
Do you need more?

**Comment by MaEtUgR** [comment]
I think it's not only for racers, at least it clearly helped the F450 a lot and I extrapolate from there.

**Comment by hamishwillee** [comment]
Closing. Outputs now mapped through actuator screen (and this work was done anyway).
