### ISSUE TITLE
Makefile:39: *** YOU HAVE TO USE GIT TO DOWNLOAD THIS REPOSITORY. ABORTING.。

### ISSUE THREAD

**Issue by zhangshuaiqing** [PX4/PX4-user_guide#2813]
When I try command
make px4_sitl_default gazebo
It returns
Makefile:39: *** YOU HAVE TO USE GIT TO DOWNLOAD THIS REPOSITORY. ABORTING.。
What should I do to solve this problem?

**Comment by hamishwillee** [comment]
The error implies that you got the PX4 source file by creating a ZIP file (say) and downloading the source that way. You MUST follow the instructions and use GIT to get the source code.

I'm going to close this, but the short answer is that you get the source by following these instructions https://docs.px4.io/main/en/dev_setup/building_px4.html#download-the-px4-source-code
