### ISSUE TITLE
I have run into a problem running command git submodule update --init --recursive

### ISSUE THREAD

**Issue by zhangshuaiqing** [PX4/PX4-user_guide#2832]
When I run command git submodule update --init --recursive, then as followed
zsq@zsq:~/package/PX4_about/PX4-Autopilot$ git submodule update --init --recursive
error: Server does not allow request for unadvertised object 562ee71388c493675269210f7692d8b7a8bb800d
Fetched in submodule path 'Tools/flightgear_bridge/models/TF-G2', but it did not contain 562ee71388c493675269210f7692d8b7a8bb800d. Direct fetching of that commit failed.
error: Server does not allow request for unadvertised object c278eb48e1b57e6b789242324e28581caf9ccf96
Fetched in submodule path 'src/drivers/gps/devices', but it did not contain c278eb48e1b57e6b789242324e28581caf9ccf96. Direct fetching of that commit failed.

what should I do to fix this problem?

**Comment by hamishwillee** [comment]
See my response to your other issue.
