### ISSUE TITLE
Error in the image of Hige-Level Software Architecture

### ISSUE THREAD

**Issue by federicociresola** [PX4/PX4-user_guide#2896]
I noticed that this image has not been updated after the v1.14 release because it still contains the reference of **FastRTPS** but
now we are using the **uXRCE-DDS**

https://github.com/PX4/PX4-user_guide/blame/e62e933def6da6655bfec5d21fba0535deacf4d3/en/concept/architecture.md#L20

**Comment by hamishwillee** [comment]
Thanks @federicociresola 

@beniaminopozzan Would you be happy with a fix to the diagram like this:
![image](https://github.com/PX4/PX4-user_guide/assets/5368500/8c006ebb-8622-45a6-9359-ba8d6d2c8618)

The bit I am not sure about is the "CDR serialization". I mean should we be talking about ROS2 here?

**Comment by beniaminopozzan** [comment]
Thank @federicociresola

**Comment by beniaminopozzan** [comment]
@hamishwillee , according to https://www.eprosima.com/index.php/products-all/eprosima-micro-xrce-dds (architecture section), I would put _micro CDR_ serialization or nothing. Just "via UART/UDP" like on the MAVLink block.

We don't mention the possible targets of MAVLink, then in my opinion we shuld not talk about ROS2.

**Comment by hamishwillee** [comment]
All done thanks. Fixed by #2896
