### ISSUE TITLE
typo : FW_RR -> FW_PR 

### ISSUE THREAD

**Issue by ParamDeshpande** [PX4/PX4-user_guide#2953]
There's a typo in manual tuning for FW. For pitch tuning, mentions roll parameters to be minimum instead. 
Corrections - > FW_RR* should be made  FW_PR* minimum in [pitch section.](https://docs.px4.io/main/en/config_fw/pid_tuning_guide_fixedwing.html#gains-to-set-to-minimum-values-2)

**Comment by hamishwillee** [comment]
Would you like to PR in a change?

**Comment by hamishwillee** [comment]
Thanks. Fixed by https://github.com/PX4/PX4-user_guide/pull/2962
