### ISSUE TITLE
运行MAVROS Offboard 控制示例 (Python)时出现WARN

### ISSUE THREAD

**Issue by dcexy** [PX4/PX4-user_guide#2961]
[ WARN] [1701914248.600585872, 21.443000000]: CMD: Unexpected command 176, result 0
WARN [mc_pos_control] Offboard activation failed with error: Activation Failed
WARN [mc_pos_control] Position-Ctrl activation failed with error: Activation Failed
WARN [mc_pos_control] Altitude-Ctrl activation failed with error: Activation Failed
[ WARN] [1701914248.658427376, 21.479000000]: PositionTargetGlobal failed because no origin

**Comment by hamishwillee** [comment]
Unless this refers to a specific document, you're best off asking on the discuss server.
