### ISSUE TITLE
Wrong Env name for PX4 standalone run

### ISSUE THREAD

**Issue by VitaliiHrozynskyi** [PX4/PX4-user_guide#3002]
On the [docs page](https://docs.px4.io/main/en/sim_gazebo_gz/) it says:
`You start PX4 in standalone mode by prefixing the make command with GZ_PX4_STANDALONE=1:`

But its `PX4_GZ_STANDALONE`.

**Comment by hamishwillee** [comment]
Thanks very much. Fixed by #3003
