### ISSUE TITLE
Broken QGroundControl related links

### ISSUE THREAD

**Issue by antonio-sc66** [PX4/PX4-user_guide#3020]
Hi, I've seen that multiple links related to QGC are broken in the docs.

Examples: 
- https://github.com/PX4/PX4-user_guide/pull/3019
- https://docs.px4.io/main/en/config/radio.html#further-information -> https://github.com/PX4/PX4-user_guide/pull/3022
- https://docs.px4.io/main/en/config/joystick.html#enabling-px4-joystick-support -> https://github.com/PX4/PX4-user_guide/pull/3021

This is related to the new docs page. If it's general maybe an automatic solution or a general link search has to be done

**Comment by hamishwillee** [comment]
Thanks. Leaving this open as I will do a full check in a couple of weeks when I get back.
