### ISSUE TITLE
Introduction of the Kconfig definition file in "Development/Writing your First Application" is incorrect

### ISSUE THREAD

**Issue by georgenwpu** [PX4/PX4-user_guide#3093]
The title of the incorrect content is "First Application Tutorial (Hello Sky)".

In the Minimal Application section, Step 4. The original content is:
_Create and open a new Kconfig definition file named Kconfig and define your symbol for naming (see [Kconfig naming convention](https://docs.px4.io/main/en/hardware/porting_guide_config.html#px4-kconfig-symbol-naming-convention)). Copy in the text below:_
```
P
"
n
-
p
```

The code is the last letter of each line. The correct code should be:
```
menuconfig EXAMPLE_PX4_SIMPLE_APP
    bool "PX4_SIMPLE_APP"
    default n
    ---help---
        Enable support for px4_simple_app
```

**Comment by hamishwillee** [comment]
@georgenwpu Thanks very much for taking the time to report this. Fixed in https://github.com/PX4/PX4-user_guide/pull/3103
