### ISSUE TITLE
A conflict between the table and the right menu

### ISSUE THREAD

**Issue by federicociresola** [PX4/PX4-user_guide#3190]
Hi,
I noticed in the [offboard page](https://docs.px4.io/main/en/flight_modes/offboard.html#description) that there is the table are creating conflict with the right menu and it doesn't allow to click on the links that there are the last column of the table. 

Browser: **Firefox 124.0.2**

![image](https://github.com/PX4/PX4-user_guide/assets/22128232/0af76975-57f4-487c-be21-7c9f641078e4)

Sorry, I don't have time to fix this error with a PR hence I decided to create this issue to point out this problem

**Comment by hamishwillee** [comment]
Thank you. I don't consider this a defect because you can scroll the page down and then you will be able to click the links. I could perhaps make the panel more opaque to make this more obvious though. I will think on it.
