### ISSUE TITLE
Doc Bug: Airspeed

### ISSUE THREAD

**Issue by MariliG** [PX4/PX4-user_guide#325]
In  [Airspeed > Testing](https://docs.px4.io/en/config/airspeed.html#testing) it says:

> fter calibration a quick test is to press your finger against the tip of the pitot and hold it. You should see the system read and hold a positive airspeed until you release.

But where/how do you see the "system read and hold a positive airspeed"? Ie where on QGC and you observe the airspeed after calibration?

**Comment by hamishwillee** [comment]
These words no longer exist - it was updated.
