### ISSUE TITLE
GitHub Repository Link Shows 404

### ISSUE THREAD

**Issue by flyingthingsintothings** [PX4/PX4-user_guide#3263]
Just creating a tiny issue because the link in the repository summary does not work and shows a 404 instead.

**The link**
![image](https://github.com/PX4/PX4-user_guide/assets/160142177/8e0f6d4f-10c0-425e-97fa-e6a0065f7ac8)

**The error**
![image](https://github.com/PX4/PX4-user_guide/assets/160142177/924807bf-0d5c-4fdb-8a15-4b774b7fccea)

**Comment by hamishwillee** [comment]
Thanks! Fixed
