### ISSUE TITLE
Various ROS links are broken

### ISSUE THREAD

**Issue by CursedRock17** [PX4/PX4-user_guide#3303]
Around the user guide, there are various ROS 2 documentation links that are broken, mainly in part due to using index.ros.org opposed to docs.ros.org (where documentation is hosted for each ROS package). [A search](https://github.com/search?q=repo%3APX4%2FPX4-user_guide%20index.ros.org&type=code) for the site shows various spots, for instance [here](https://github.com/PX4/PX4-user_guide/blob/82f860792a0ef0f6c21aede49ac96d9eec8dc635/en/ros2/user_guide.md?plain=1#L127):
> https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/.

should instead be:
> https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html

I currently don't have the bandwidth to solve this, but it's a simple solution, perhaps great for new contributors.

**Comment by hamishwillee** [comment]
Thank you. Fixed by #3305
