### ISSUE TITLE
Unable to run 'make px4_sitl gazebo-classic

### ISSUE THREAD

**Issue by iftikharumrani** [PX4/PX4-user_guide#3309]
Hi folks, I am using WSL 2 "Ubuntu 20.04", successfully cloned PX4 autopilot by following [instruction.](https://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html) I'm trying to run the [gazebo classic](https://docs.px4.io/main/en/sim_gazebo_classic/) simulation, but its not making any progress, can be seen in the following

iftikhar@DESKTOP-GH9UI2B:~/PX4-Autopilot$ make px4_sitl gazebo-classic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3")
-- PX4 config file: /home/iftikhar/PX4-Autopilot/boards/px4/sitl/default.px4board
-- PLATFORM posix
-- ROMFSROOT px4fmu_common
-- ROOTFSDIR .
-- TESTING y
-- ETHERNET y
-- ROOT_PATH ./
-- PARAM_FILE /fs/mtd_params
-- PX4 config: px4_sitl_default
-- PX4 platform: posix
-- PX4 lockstep: enabled
-- The CXX compiler identification is GNU 9.4.0
-- The C compiler identification is GNU 9.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- cmake build type: RelWithDebInfo
/usr/bin/python3: Error while finding module specification for 'symforce.symbolic' (ModuleNotFoundError: No module named 'symforce')
-- Could NOT find gz-transport (missing: gz-transport_DIR)
-- Could NOT find gz-transport (missing: gz-transport_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'bullet>=2.82'
--   Found bullet, version 2.88

.
.
.
.
.
.

[49/143] Generating /home/iftikhar/PX4-Autopilot/Tools/sim...classic/sitl_gazebo-classic/models/tiltrotor/tiltrotor.sdf
/home/iftikhar/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models/tiltrotor/tiltrotor.sdf.jinja -> /home/iftikhar/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models/tiltrotor/tiltrotor.sdf
[50/143] Generating /home/iftikhar/PX4-Autopilot/Tools/sim...o-classic/models/uuv_bluerov2_heavy/uuv_bluerov2_heavy.sdf
/home/iftikhar/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models/uuv_bluerov2_heavy/uuv_bluerov2_heavy.sdf.jinja -> /home/iftikhar/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models/uuv_bluerov2_heavy/uuv_bluerov2_heavy.sdf
[143/143] Linking CXX shared library libgazebo_user_camera_plugin.so
[999/1000] cd /home/iftikhar/PX4-Autopilot/build/px4_sitl_...opilot /home/iftikhar/PX4-Autopilot/build/px4_sitl_default
SITL ARGS
sitl_bin: /home/iftikhar/PX4-Autopilot/build/px4_sitl_default/bin/px4
debugger: none
model: iris
world: none
src_path: /home/iftikhar/PX4-Autopilot
build_path: /home/iftikhar/PX4-Autopilot/build/px4_sitl_default
GAZEBO_PLUGIN_PATH :/home/iftikhar/PX4-Autopilot/build/px4_sitl_default/build_gazebo-classic
GAZEBO_MODEL_PATH :/home/iftikhar/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models
LD_LIBRARY_PATH :/home/iftikhar/PX4-Autopilot/build/px4_sitl_default/build_gazebo-classic
empty world, setting empty.world as default
Using: /home/iftikhar/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models/iris/iris.sdf
 
 
[Showing no progress after the final script]
Can you please suggest the solutions.

**Comment by hamishwillee** [comment]
@iftikharumrani I've just tried this from scratch and it all worked on my Windows 11 using current `main` branch. I'm not sure what to suggest. You might want to ask on the discussion boards/forums for ideas?

Sorry I can't help.
