### ISSUE TITLE
404 on docs.px4.io

### ISSUE THREAD

**Issue by martinbaer** [PX4/PX4-user_guide#3508]
I'm getting a 404 on https://docs.px4.io/main/

Is this happening to anyone else?

![image](https://github.com/user-attachments/assets/47de99d7-0896-4f84-9e3e-53aa9abfa95f)

**Comment by farhangnaderi** [comment]
> I'm getting a 404 on https://docs.px4.io/main/
> 
> Is this happening to anyone else?
> 
> ![image](https://private-user-images.githubusercontent.com/60465423/396307366-47de99d7-0896-4f84-9e3e-53aa9abfa95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzOTY2NzYsIm5iZiI6MTczNDM5NjM3NiwicGF0aCI6Ii82MDQ2NTQyMy8zOTYzMDczNjYtNDdkZTk5ZDctMDg5Ni00Zjg0LTllM2UtNTNhYTlhYmZhOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAwNDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOTYyOGNmZGRhMDBjYTVhYjQ0MGNlNWQwNjZjMmNhMzMyZjg4MWNiOWQzYzEwZjNkZWU2NGFmNjJiYjJmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fKUynyjZPWfEX4NR4jeZkdZ0l4LEjCAA91o6YZw5fl8)

It seems to be ok now: 

![image](https://github.com/user-attachments/assets/52280a9c-c12a-4f79-b45b-e40f231111fd)

**Comment by martinbaer** [comment]
Ah thanks, it's back up

**Comment by hamishwillee** [comment]
Yeah sorry about that. If stopped deploying 5 days ago and got stuck publishing a build from 9 months ago. Had to reset the deployment repo to get it to all work again.
