### ISSUE TITLE
Airframe config for tricopter configuration not correct

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/PX4-user_guide#725]
Inoticed that the airframe config for the tricopter airframe have incorrect prop directions. 

As in: https://docs.px4.io/master/en/airframes/airframe_reference.html#tricopter-y

@hamishwillee How is the image generated? The prop layout is only marked on the image and I am not sure how we can change this

**Comment by sfuhrer** [comment]
The direction of the propellers isn't taken into account by the software, we should add this comment there. And also change the picture to have the front propellers turning in opposite directions, as this is how you do it for all systems I know.

**Comment by hamishwillee** [comment]
This page is built from the airframe definititon - so any comments have to be added there.

I actually don't know where/how these images are created, but they need to also be changed in the Devguide and in QGC. 

@bkueng Do you know where the images come from/what tools are used to create them?

**Comment by bkueng** [comment]
I used inkscape in the past, but don't know where they come from.

**Comment by hamishwillee** [comment]
@julianoes Any ideas on where we get images for the airframes - or who might know?

**Comment by julianoes** [comment]
> @julianoes Any ideas on where we get images for the airframes - or who might know?

No idea.

**Comment by DanAbara** [comment]
Hi @hamishwillee , I will like to help with this issue. Please assign to me. I did some checks and the images used in the airframe configs are in https://github.com/PX4/PX4-user_guide/tree/master/assets/airframes/types. 

As per @sfuhrer's comments, I've modified the images so that the front propellers turn in opposite directions. 

                          
![YMinus2](https://user-images.githubusercontent.com/44237659/125201006-3f822480-e265-11eb-8bc6-3520117bc608.png) ![YPlus2](https://user-images.githubusercontent.com/44237659/125201009-401abb00-e265-11eb-97a3-724857b19739.png)

              Tri Y-                           Tri Y+

Before I create a PR, just to confirm, should we have this setup (front propellers in opp. directions) as an alternative to the existing config ?, since either of them should work. Or should I just replace the existing images with this one. Thank you.

**Comment by Jaeyoung-Lim** [comment]
@DanAbara Shouldn't the colors indicate the turning directions of the prop?

**Comment by DanAbara** [comment]
> @DanAbara Shouldn't the colors indicate the turning directions of the prop?

You're right. I've modified them.

![YMinus2](https://user-images.githubusercontent.com/44237659/125202940-f6829e00-e26d-11eb-9322-2324f8b03ec9.png) ![YPlus2](https://user-images.githubusercontent.com/44237659/125202941-f71b3480-e26d-11eb-8e07-0eb14f313ffd.png)

@Jaeyoung-Lim so should I add these alternative setups or just replace the existing ones?

**Comment by hamishwillee** [comment]
I'm back on Wednesday and will think a bit more on this. My initial reaction though is that this may well be a new config. The images would also need to go through to QGC.

**Comment by DanAbara** [comment]
Alright @hamishwillee, just point me in the right direction when you're back and i'm happy to make the necessary changes.

**Comment by hamishwillee** [comment]
@DanAbara Awesome. As you already worked out, all you need to do is create a PR that replaces YMinus.svg and YPlus.svg with your (same name) versions in https://github.com/PX4/PX4-user_guide/tree/master/assets/airframes/types
I have assigned to you.

As a separate task, it would be good to also update the images here: https://github.com/mavlink/qgroundcontrol/tree/master/src/AutoPilotPlugins/Common/Images - though these appear not to include arrow directions

**Comment by DanAbara** [comment]
@hamishwillee, PR created. I've updated the images in QGC as well without the arrows and created a PR for that as well as well.

**Comment by hamishwillee** [comment]
Thanks. I've reviewed the docs PR. Up to QGC folks to review the other. If nothing happens in a week or so on that ping me.
