### ISSUE TITLE
DeveloperBug: Flight Modes · PX4 Developer Guide

### ISSUE THREAD

**Issue by 1AwesomeDeveloper** [PX4/PX4-user_guide#979]
DESCRIBE PROBLEM WITH DOCS HERE

Bug Page: [Flight Modes · PX4 Developer Guide](https://dev.px4.io/master/en/concept/flight_modes.html#flight-mode-evaluation-diagram)

In RTL it should be return to launch instead of return to land

**Comment by hamishwillee** [comment]
Thanks. Fixed in https://github.com/PX4/PX4-user_guide/commit/ab3208f25863755acf5b712fc07ef8fd77f86409
